### ISSUE TITLE
Debugging jasmine_node_test is hard

### ISSUE THREAD

**Issue by mprobst** [bazelbuild/rules_nodejs#102] opened 2018-02-01 14:08 UTC
jasmine_node_test runs, but then immediately terminates and just exits. `ibazel run :my_nodejs_test` keeps re-running (at least often), but the NodeJS virtual machine still exits in between. That makes it hard to attach a debugger to the VM *and* see all the files that are loaded *and* actually set breakpoints in them.

**Comment by alexeagle** [comment] 2018-02-01 23:41
yeah under `bazel run` it should behave like `ts_web_test` and keep the nodejs process running, just re-loading js files from the runfiles.

**Comment by alexeagle** [comment] 2018-05-12 17:15
Dupe of #177

**Closed by alexeagle** 2018-05-12 17:15 UTC
Labels: enhancement
