### ISSUE TITLE
rollup_bundle doesn't support module_name with more then 2 segments

### ISSUE THREAD

**Issue by jbedard** [bazelbuild/rules_nodejs#1261] opened 2019-10-10 18:13 UTC
While linking the modules any `ng_module(module_name)`/`ts_library(module_name)` gets linked in based on that name, but there is a [2-segment restriction](https://github.com/bazelbuild/rules_nodejs/commit/94abf68#diff-ba12e7c9523323f8d5f10aa8a99d35dbR312) on that name to follow the node/npm conventions.

In terms of *npm* module names this restriction is correct. But previously `ng_module(module_name)` and `ts_library(module_name)` could be used in various ways beyond npm (or at least that's how I thought of it), essentially as aliases or AMD/CJS names etc.

**Comment by moczix** [comment] 2019-10-11 05:57
yeah, i use module_nam as path alias from tsconfig. And nowe we got this error

**Comment by alexeagle** [comment] 2019-10-15 22:46
We want to scale back our semantics to match npm. You'll have to have more module names `@my_org/one`, `@my_org/two` or use deep imports 
`deps=["//packages/one"]` -> `import '@my_org/one/thing/two`

**Comment by moczix** [comment] 2019-10-16 05:05
the problem is, that bazel dont read paths from tsconfig, thats why we use module_name with name starting exactly like alias. I tried now, to remove module_name at all and it dont work. I tried diffrent combinations, like have module_name with one segment, two segments and dont work. The main problem is that bazel dont read paths from tsconfig

**Comment by Toxicable** [comment] 2019-10-17 18:12
@ashi009 You can have a high level module name with deep import paths.
Say you have a module `@my-wksp/lib1` and you want to make the import `import {SomeClass} from @my-wksp/lib1/lvl1/lvl2'`

You'd start by defining the module at it's root to be `@my-wksp/lib1`.
You'd make sure that this package includes and compiles all files down in `lvl1` and `lvl2`
or
You'd make sure it depends other targets in those lower levels, making it more fine grained.

That way it hold sematics with npm and is easy to do.
Does that fit your use case?
>say export * from '/absolute/path/to/the/resolved/entry/point'

This wouldn't work since if the user tried to make a deep import it would bypass that generated import and the fiels woudln't exist, also inter-node_module requires wouldn't work either.

**Comment by jbedard** [comment] 2019-10-17 18:39
> You'd make sure that this package includes and compiles all files down in lvl1 and lvl2
> or
> You'd make sure it depends other targets in those lower levels, making it more fine grained.

That's what I'm trying to avoid, to keep the dependencies fine-grained. But I also want pretty import statements (aliases to avoid absolute paths), this is really the only reason I've been using `module_name`...

Normally (outside bazel) I've done this with the tsconfig.json `paths` option, but I believe `ts_library` ignores this, and `rollup_bundle` won't know of it at all.

**Comment by gregmagolan** [comment] 2019-10-23 18:29
Closed via #1281

**Closed by gregmagolan** 2019-10-23 18:29 UTC
