### ISSUE TITLE
googmodules example fails to compile prodmode with worker

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_nodejs#987] opened 2019-01-31 20:43 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library

### Is this a regression?

 Yes.

### Description

The prodmode compile of the googlemodules example fails while trying to write `.externs.js` when run in a worker.

## 🔬 Minimal Reproduction

1. Checkout the latest release (https://github.com/bazelbuild/rules_typescript/releases/tag/0.22.1)
2. Run `bazel build //examples/googmodule --output_groups=es6_sources`
3. Notice compile error
4. Comment out `build --strategy=TypeScriptCompile=worker` in `.bazelrc`
5. Run `bazel build //examples/googmodule --output_groups=es6_sources` again.
6. Notice successful compile

Also note: adding `generate_externs = False,` to the `ts_library` and adding `"tsickleGenerateExterns": false,` to the `bazelOptions` in `tsconfig.json` fail to prevent the error.

## 🔥 Exception or Error

<pre><code>
ERROR: /home/jaredneil/code/rules_typescript/examples/googmodule/BUILD.bazel:5:1: Compiling TypeScript (prodmode) //examples/googmodule:googmodule failed (Exit 1)
Compilation failed Error: EACCES: permission denied, open 'bazel-out/k8-fastbuild/bin/examples/googmodule/googmodule.externs.js'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at emitWithTsickle (/home/jaredneil/.cache/bazel/_bazel_jaredneil/19dfd516ff256fd1671b6233e232dcc8/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts:323:8)
    at runFromOptions (/home/jaredneil/.cache/bazel/_bazel_jaredneil/19dfd516ff256fd1671b6233e232dcc8/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts:242:19)
    at runOneBuild (/home/jaredneil/.cache/bazel/_bazel_jaredneil/19dfd516ff256fd1671b6233e232dcc8/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_wrapped.ts:159:12)
    at Socket.<anonymous> (/home/jaredneil/.cache/bazel/_bazel_jaredneil/19dfd516ff256fd1671b6233e232dcc8/execroot/build_bazel_rules_typescript/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/worker.ts:112:26)
    at Socket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:534:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Target //examples/googmodule:googmodule failed to build
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu 18.04.1 LTS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
0.19.0
  </code>
</pre>

**Comment by alexeagle** [comment] 2019-09-30 15:29
dupe of #757

**Closed by alexeagle** 2019-09-30 15:29 UTC
Labels: package:typescript
