### ISSUE TITLE
angular-jwt.module.ngfactory.js file in node_module_library rule

### ISSUE THREAD

**Issue by agataHappy** [bazelbuild/rules_nodejs#1908] opened 2020-05-25 18:03 UTC
# 🐞 bug report

### Affected Rule
 The issue is caused by the rule: 
`node_module_library`?
`yarn_install`?

### Is this a regression?

I don't think so

### Description

In `node_module_library` rule for `@auth/angular-jwt` package, target `angular-jwt__contents`: `angular-jwt.module.ngfactory.js` is added in `named_module_srcs` which should contain only javascript named-UMD or named-AMD scripts. Because of that you can't use `ts_devserver` 

## 🔬 Minimal Reproduction

1. Add @auth0/angular-jwt to your dependencies in package.json.
2. After building your app with Bazel you should take a look in `external/npm/@auth0/angular-jwt/BUILD.bazel`

## 🔥 Exception or Error

Error shows only in browser console when you use devserver:
```
Uncaught SyntaxError: Cannot use import statement outside a module
    at ts_scripts.js:82172
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Fedora 31
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.1.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 7 13:01:04 2020 (1581080464)
Build timestamp: 1581080464
Build timestamp as int: 1581080464
Done in 0.12s.
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.6.0
  </code>
</pre>

**Comment by alexeagle** [comment] 2020-05-26 14:34
Is this a dupe of https://github.com/bazelbuild/rules_nodejs/issues/1725 ?

I see that package ships a umd bundle https://unpkg.com/@auth0/angular-jwt@4.1.2/bundles/auth0-angular-jwt.umd.js which does have a name `define('@auth0/angular-jwt', ['exports...` so it feels like your build should be picking up that one file and no others

**Comment by agataHappy** [comment] 2020-05-27 07:13
@alexeagle Possibly it is a dupe, sorry. But I have some more info I think.UMD bundle is shipped and used but for some reason ngfactory.js file is added too. So it has both umd and ngfactory. It causes problems with devserver because those files are added when app is build, not when I'm adding them to `scripts` . I know I should add only umd and amd bundles in devserver but how should I ensure that when building app files Bazel will use only umd file and not ngfactory with imports?

AFAIK, `named_module_srcs` should consist only of umd and amd (`# subset of srcs that are javascript named-UMD or named-AMD scripts` comment above it) so why Bazel added ngfactory.js too?

**Comment by alexeagle** [comment] 2020-05-29 02:37
I think you should change the label to just that one file and not the named_module_srcs. It has some angular-specific logic to pick up the factory files IIRC

**Comment by agataHappy** [comment] 2020-06-04 13:22
@alexeagle Some news? Will you take a look?

**Comment by alexeagle** [comment] 2020-06-04 14:48
Did you try making the change I suggested? 

if you can't figure out what change to make you could post a minimal repro in the form of a PR adding a usage of this library to our example.

**Comment by agataHappy** [comment] 2020-06-09 11:13
Sorry for late reply, I made small repo that should show you where the problem is: https://github.com/agataHappy/angular-jwt-error-example

**Comment by evahowe** [comment] 2020-06-17 20:32
Thanks @agataHappy - I am putting labels on it so that it gets put in line.

**Comment by agataHappy** [comment] 2020-09-04 10:14
@evahowe Any update about that bug? :slightly_smiling_face:

**Comment by agataHappy** [comment] 2020-11-04 17:14
@evahowe Did you take a look at this bug? Any news?

**Comment by lovepocky** [comment] 2020-11-14 11:01
same issue

**Closed** 2021-05-10 02:29 UTC
Labels: Can Close?, bug, need: investigation
