### ISSUE TITLE
no such package '': BUILD file not found

### ISSUE THREAD

**Issue by dv29** [bazelbuild/rules_nodejs#869] opened 2019-06-16 02:21 UTC
# 🐞 bug report

### Affected Rule
The issue is caused by the rule: ts_library 

### Description
With the following directory structure building the project doesn't work
workspace -> src -> services -> node (Build)

## 🔬 Minimal Reproduction
https://github.com/dv29/fullstack-bazel
running `bazel build //src/services/node/...` throws the error

## 🔥 Exception or Error

<pre><code>
ERROR: /home/user/Projects/fullstack-bazel/src/services/node/BUILD:11:1: no such package '': BUILD file not found on package path and referenced by '//src/services/node:my_app'
ERROR: Analysis of target '//src/services/node:my_app' failed; build aborted: no such package '': BUILD file not found on package path
INFO: Elapsed time: 0.106s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux 4.15.0-51-generic #55-Ubuntu SMP x86_64 GNU/Linux
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 0.26.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jun 6 11:05:05 2019 (1559819105)
Build timestamp: 1559819105
Build timestamp as int: 1559819105
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
rules_nodejs-0.31.1 e04a82a72146bfbca2d0575947daa60fda1878c8d3a3afe868a8ec39a6b968bb
  </code>
</pre>

**Comment by Toxicable** [comment] 2019-06-16 04:13
`ts_library` by default sets the `tsconfig` attribute to `//:tsconfig.json`
Since you don't have a BUILD file in your workplace root, bazel cant find the tsconfig.json

**Comment by dv29** [comment] 2019-06-16 13:19
is there a way to configure it? because I'll have multiple ts apps in this workplace with different configurations

**Comment by dv29** [comment] 2019-06-16 20:56
nevermind, figured it out had to pass it as parameter, thanks.
I had been pulling my hairs out because of this. the error was really throwing me off

**Comment by dv29** [comment] 2019-06-17 13:43
How can I add multiple managed directories for multiple ts apps in same workspace?

**Comment by alexeagle** [comment] 2019-06-17 15:02
looks like the root cause here was a bad error message which should be fixed in the next bazel release:
https://github.com/bazelbuild/bazel/issues/7854

to have multiple managed directories, you just need multiple package.json+lockfile pairs in subdirectories, call `yarn_install` or `npm_install` on each, and list all of them in `managed_directories` - see https://github.com/alexeagle/demo-bazel-multipackage

**Closed by alexeagle** 2019-06-17 15:02 UTC

**Comment by dv29** [comment] 2019-06-17 15:45
@alexeagle thanks for the help

**Comment by dv29** [comment] 2019-06-18 14:20
I got the node app with ts working however I cannot get the react app working. I have updated the github project. I added the multipackage configurations and could get it to build but its not finding the dependencies of the project from project node_modules.

I get module not found errors and if I added it to deps on ts_library rule it gives `All npm dependencies need to come from a single workspace. Found 'external/npm/node_modules' and 'external/web/node_modules'.`
How can I provide project deps for particular project.

**Comment by zoidbergwill** [comment] 2019-11-06 21:17
@dv29 Based on some input from here: https://github.com/angular/angular-bazel-example/issues/456#issuecomment-501381665

You'll have to override `node_modules` and `compiler` for any `ts_library` rules, since they hardcode `@npm`: https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/src/internal/build_defs.bzl#L25-L26

**Comment by zoidbergwill** [comment] 2019-11-06 21:18
But if you have `web1` that also consumes `lib1` and they have their own package.json and yarn.lock's then you get a similar error too. Haven't figured out how to get past that one yet.
