### ISSUE TITLE
Allow ts_project to generate a TreeArtifact

### ISSUE THREAD

**Issue by Aghassi** [bazelbuild/rules_nodejs#2386] opened 2021-01-06 19:37 UTC
Currently, is using `pkg_npm` to try and merge outputs from say `babel` and `ts_project`, it fails because `ts_project` doesn't generate a tree artifact and `babel` is autogenerated `index.bzl` file that does support tree artifacts.

**Comment by mattem** [comment] 2021-01-07 15:25
Does it work if the output of `ts_project` is passed though a `filegroup`? 

```
ts_project(
   name = "ts",
   ...
)

filegroup(
   name = "files",
   srcs = [":ts", ...],
   ...
```

**Comment by Aghassi** [comment] 2021-01-11 17:04
As discussed on slack, it does not work this way (that's what I originally had tried)

**Comment by alexeagle** [comment] 2021-01-12 20:08
https://bazelbuild.github.io/rules_nodejs/TypeScript.html#alternatives
> The only reason to use raw tsc is if you want to compile an opaque directory of .ts files and cannot enumerate them to Bazel. (For example if the .ts files are generated by some tool). This will produce an opaque directory of .js file outputs, which you won’t be able to individually reference. 

I think maybe we should close this as working as intended?

**Closed** 2021-01-27 02:10 UTC
Labels: Can Close?, package:typescript
