### ISSUE TITLE
Failed to load typedefs for scoped package with mangled name

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_nodejs#1334] opened 2019-11-05 13:59 UTC
# 🐞 bug report

### Affected Rule

`ts_library`

### Is this a regression?

N/A

### Description

If a scoped package doesn't have typedefs built-in, typescript will try to search typedefs in `@types/@scoped/package` and `@types/scoped__package` for type definitions. However, the former search will be done using paths defined, while the latter will be one solely in `node_modules` and tsc_wrappeed's file cache will report non-exist.

Debugging logs from tsc_wrappeed's worker.js:

```
updating digests: Map {
...
  '/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/xrc/external/npm/node_modules/@types/babel__core/index.d.ts' => '38623637343866396531356164376261633439346463336364336231336261306138626531393561636139376637633130613936623163373461393536663332',
...
  '/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/xrc/external/npm/node_modules/@types/babel__core/package.json' => '39346662613733623232646138323830346331643633316136396537623335343138353462333730313037653266303562386639613161656433383834646238',
...
}
Path exists, but is not registered in the cache /private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/<ws>/node_modules/@babel/core/package.json
Path exists, but is not registered in the cache /private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/<ws>/node_modules/@types/babel__core/package.json
```

(This sounds like a tsc resolver logic bug, but it's very unlikely to reproduce in non-bazel environment. I'll file a separate bug for them.)

## 🔬 Minimal Reproduction

index.ts

```ts
import * as babel from '@babel/core';
```

BUILD.bazel

```python
ts_library(
    name = "ts_default_library",
    srcs = ["index.ts"],
    deps = [
        "@npm//@babel/core",
        "@npm//@types/babel__core",
    ],
)
```

## 🔥 Exception or Error

```
<redacted>/index.ts:1:24 - error TS7016: Could not find a declaration file for module '@babel/core'. '/private/var/tmp/_bazel_xiaoyi/2258f168242f85dcc9f2c0d3e9d2258a/execroot/<ws>/external/npm/node_modules/@babel/core/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/babel__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@babel/core';`

1 import * as babel from '@babel/core';
                         ~~~~~~~~~~~~~
```

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS 10.15.1
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
$ bazel version
Build label: 0.27.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:03:58 2019 (1560776638)
Build timestamp: 1560776638
Build timestamp as int: 1560776638
  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>
0.39.1
  </code>
</pre>

**Anything else relevant?**

**Comment by ashi009** [comment] 2019-11-05 14:35
https://github.com/microsoft/TypeScript/issues/34917

**Comment by greenboxal** [comment] 2020-07-05 16:02
It seems like `tsc` is hard coded to respect standard node_modules resolution (see https://github.com/microsoft/TypeScript/issues/34917#issuecomment-653906036).

A temporary fix we could implement is to mangle the file names (or the entire node_modules traversal) ourselves on `tsc_wrapped/compiler_host.ts`. It's hacky but probably works?

**Comment by alexeagle** [comment] 2020-07-05 17:03
A root cause here is that `ts_library` is designed for Google's internal use case where there is no node_modules directory. Changes to rules_typescript are hard to land because Google doesn't have this problem, and they don't want to add hacky code to their codebase. `ts_project` is designed to solve this, so I think maybe it will never be fixed in `ts_library`, unless someone feels motivated to get past this governance issue.

**Comment by willfrew** [comment] 2021-02-05 01:25
@alexeagle I just opened microsoft/Typescript#42658 to attempt to fix the issue in the compiler itself however I was unable to get `ts_library` to build with my locally built binary (using the `compiler` arg)

Current setup:
`WORKSPACE`
```starlark
...
new_local_repository(
    name = "typescript",
    path = "../../microsoft/TypeScript",
    build_file = "BUILD.localtsc",
)
```
`BUILD.localtsc`
```starlark
package(default_visibility=["//visibility:public"])
load("@build_bazel_rules_nodejs//:index.bzl", "nodejs_binary")

nodejs_binary(
  name = "local_tsc",
  entry_point = "built/local/tsc.js",
  data = glob(["built/**/*", "node_modules/*"]),
)
```

`package/test/BUILD`
```starlark
package(default_visibility=["//visibility:public"])
load("@npm//@bazel/typescript:index.bzl", "ts_library")

ts_library(
    name = "test_lib",
    compiler = "@typescript//:local_tsc",
    supports_workers = False,
    srcs = glob(["src/**/*.ts"]),
    deps = [
      "@npm//@types/koa__cors", # <-- The package I hit this issue with 
    ],  
)
```

The error with a `bazel build //packages/test:all` is:
```
error TS6054: File 'bazel-out/k8-fastbuild/bin/packages/api-gateway/api-gateway_es5_tsconfig.json' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
  The file is in the program because:
    Root file specified for compilation
```
Which suggests to me that `ts_library` is assuming a "wrapped_tsc" / one that takes parameters slightly differently.

Any ideas how I could perhaps wrap my tsc?

**Closed** 2021-05-23 02:42 UTC
Labels: Can Close?, bug, package:typescript
