### ISSUE TITLE
packages/esbuild: Rename flag error-limit to log-limit

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/rules_nodejs#2578] opened 2021-03-31 01:42 UTC
# 🐞 bug report

### Affected Rule

The issue is caused by the rule:  `packages/esbuild`

### Is this a regression?

No.

### Description

Esbuild has unexpectedly introduced this change https://github.com/evanw/esbuild/commit/7d30f836e372dde407b8b0961d2deb9ec971c342 where the flag `error-limit` has been renamed to `log-limit`. This breaks builds using any versions after this commit was introduced. For example, v0.11.21.

## 🔬 Minimal Reproduction

Try to build any examples which use esbuild using esbuild v0.11.2.

## 🔥 Exception or Error

<pre><code>Use --sandbox_debug to see verbose messages from the sandbox
 > error: Invalid build flag: "--error-limit=0"</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre><code>uname -a
Darwin &lt;redacted&gt; 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64</code></pre>

**Output of `bazel version`:**

<pre><code>Build label: 4.0.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sat Jan 23 02:12:39 2021 (1611367959)
Build timestamp: 1611367959
Build timestamp as int: 1611367959</code></pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre><code>3.2.3</code></pre>

**Anything else relevant?**

**Comment by mattem** [comment] 2021-03-31 02:03
Duplicate of https://github.com/bazelbuild/rules_nodejs/issues/2552, see linked PR.

**Closed by mattem** 2021-03-31 02:03 UTC
