### ISSUE TITLE
Cannot Reference rules_nodejs Source Directly

### ISSUE THREAD

**Issue by Dig-Doug** [bazelbuild/rules_nodejs#1077] opened 2019-09-01 13:40 UTC
# 🐞 bug report

### Affected Rule

`web_package`

### Is this a regression?

Yes, older versions, e.g. 0.30.2, did not have this issue

### Description

Hi,

Today I encounted an issue while updating my fork of rules_nodejs to the latest version:

```
...every rule of type web_package implicitly depends upon the target '@build_bazel_rules_nodejs//internal/web_package:assembler', but this target could not be found because of: error loading package '@build_bazel_rules_nodejs//internal/web_package': Unable to find package for @npm_bazel_jasmine//:index.from_src.bzl: The repository '@npm_bazel_jasmine' could not be resolved.
```

After doing some debugging, I believe this is happening because of the `BEGIN-INTERNAL` lines [here](https://github.com/bazelbuild/rules_nodejs/blob/master/internal/web_package/BUILD.bazel#L4).

The issue is that I cannot build rules_nodejs directly from source -- I have to use a release build, which is very cumbersome when you are patching this project. Normally, the way I develop a patch for a library is:

- Fork and clone the repo locally
- Reference it in my main project as a `local_repository`
- Write the libary code, in this case `rules_nodejs`
- Build my main project, make sure it works
- Commit + open PR

PRs can take weeks to get submitted. While I wait, I update my project to reference my fork via an `http_archive` instead of a `local_respository` so I can use the changes immediately. However, because I can't just reference the source in my project, I can't do this anymore. Instead, I need to create my own release build *every* time I make a change.

Do you have an alternate setup that you use when referencing this library from another project?

If not, is there an alternative to `BEGIN-INTERNAL`, maybe using `select()`?

Let me know if you have any ideas, I'm happy to take a stab at fixing this.

Thanks!

**Comment by alexeagle** [comment] 2019-09-11 21:43
A couple options:
- the easiest thing is probably to turn your PR into a patch against the distribution, then use bazel's `patches` attribute on http_archive to swap out the contents on fetch. You'd end up checking in some `*.patch` files in your repo. Example: https://github.com/angular/angular/blob/bb9e61202cb4e4168407bac3f025dfdbf986b891/WORKSPACE#L23

- you should be able to use this repo from source like you're doing, but then you do need all the packages available. Your `WORKSPACE` file should have a `local_repository(name="@npm_bazel_jasmine")` somewhere like we do:
https://github.com/bazelbuild/rules_nodejs/blob/14003a0a0f65eb9a596e8e168d6e6b3b41997d6f/WORKSPACE#L46-L51

**Comment by alexeagle** [comment] 2019-09-11 21:43
I'll close this as Working as Intended but please reply if this isn't enough to get you unstuck

**Closed by alexeagle** 2019-09-11 21:43 UTC

**Comment by gonzojive** [comment] 2020-03-23 01:18
@alexeagle, would you be willing to put together an example project that loads a forked version of rules_nodejs from a git_repository or local_repository?

I'm trying to use the latest version of rules_nodejs (tip of master) because of the improved `ts_proto_library` rule. The required changes to my project's WORKSPACE file to get this working are somewhat onerous. It seems even with the NESTED_PACKAGES excerpt, there are numerous errors.

**Comment by javatlacati** [comment] 2021-07-10 18:45
When I try to build this repo: https://github.com/javatlacati/kimeracss/tree/bazel
I got the following error:

```
ERROR: Error fetching repository: java.io.IOException: No WORKSPACE file found in C:/users/ruslanlopez/_bazel_000262781/z3giu6et/external/npm_bazel_jasm
ine
ERROR: no such package '@npm_bazel_jasmine//': No WORKSPACE file found in C:/users/ruslanlopez/_bazel_000262781/z3giu6et/external/npm_bazel_jasmine
INFO: Elapsed time: 53.616s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: test/scss/base
```

local repository config on workspace file:

```
local_repository(
    name = "npm_bazel_jasmine",
    path = "node_modules/@bazel/jasmine",
)
```

Regards.
