### ISSUE TITLE
PATH and npm_package_bin executing a nodejs_binary

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_nodejs#3119] opened 2021-12-06 03:44 UTC
# 🐞 bug report

### Affected Rule

`nodejs_binary` and `npm_package_bin`, or maybe something else.

### Is this a regression?

I don't think so.

### Description

Consider the following rules:

```
nodejs_binary(
    name = "example",
    data = [
        "lib",
        "package.json",
    ],
    entry_point = "index.ts",
)

some_npm_app(
    name = "app",
    args = [
        "--app $(execpath example.sh)",
    ],
    data = [
        "example.sh",
        "@npm//:node_modules",
    ],
    output_dir = True,
)
```

Because `some_npm_app` contains an `output_dir`, it will map to the `npm_package_bin` rule. `some_npm_app` will be called through an instance of the `launcher.sh` script, and in turn it will call `example.sh`, which is the instance of `launcher.sh` wrapping the `example` binary.

However, calling into `example.sh` results in: `env: bash: No such file or directory`

This is because `launcher.sh`'s shebang is `!/usr/bin/env bash`, but when we get to `some_npm_app.sh`, the PATH variable doesn't contain `/usr/bin`.

I'm not sure what is replacing the PATH variable, but I think it should preserve some aspects of the original value.

## 🔬 Minimal Reproduction

I can provide one if needed.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
4.1.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
4.4.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment] 2021-12-07 15:15
I think this may be a dupe of https://github.com/bazelbuild/rules_nodejs/issues/1553 ?

It's a known issue that `nodejs_binary` doesn't behave well as a tool for downstream `genrule` or `ctx.actions.run` usage.

**Comment by duarten** [comment] 2021-12-07 22:25
I'm not sure, this seems related to PATH missing e.g. /usr/local/bin, while #1553 seems more about something not being linked?

**Comment by esprehn** [comment] 2021-12-10 19:15
We have the same problem, the nodejs_binary .js code calls into some code that expects to be able to do execSync() and execute shell commands, unfortunately the PATH has been reset so even basic things like `ls` don't work.

This does seem different than the downstream deps bug #1553, the issue here is the launcher script clearing the environment PATH variable.

**Comment by alexeagle** [comment] 2022-06-12 04:51
I don't think this will ever be fixed - the maintainers are now working in https://github.com/aspect-build/rules_js/ which doesn't have this problem.

**Closed by alexeagle** 2022-06-12 04:51 UTC
Labels: bug, Can Close?
