### ISSUE TITLE
Can't Expose Port With Testcontainers in jasmine_node_test

### ISSUE THREAD

**Issue by flolu** [bazelbuild/rules_nodejs#2445] opened 2021-02-03 17:14 UTC
I would like to run integration tests with Bazel by programmatically starting Docker containers.

To do this I use a package called [testcontainers](https://github.com/testcontainers/testcontainers-node).

Everything works fine until I try to expose a port in my `docker-compose.yaml`

```
version: '3'
services:
  gateway:
    ports:
      - 3000:3000
```

But I need to expose a port to test my services.

**The Error**
```
Error: (HTTP code 409) unexpected - Container 1323d987692c32706d95fc4210a7e916c64858957fb251366de3f4c1a79bfefc is not running
```

**Minimal Reproduction**
https://github.com/flolu/bazel-testcontainers-repro

- Running `yarn test:jasmine` (without Bazel) work completely fine
- Running `yarn test` (with Bazel `jasmine_node_test` fails, but only when a port is exposed)

**Info**
As already [discussed](https://github.com/flolu/bazel-testcontainers-repro/pull/1#issue-510981474) with @cristianrgreco this is probably not an issue with testcontainers, but rather with Bazel and/or rules_nodejs.

**Relevant Code**
```
describe('integration test', () => {
  jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;

  it('starts gateway with port', async () => {
    const filepath = path.join(__dirname, '../')
    const filename = 'docker-compose.fails.yaml'
    const env = await new DockerComposeEnvironment(filepath, filename).up()
    const container = env.getContainer("repro_gateway-fails")
    console.log(container)
    const res = await axios.get(`http://${container.getHost()}:${container.getMappedPort(3000)}`)
    expect(res.data.toString()).toEqual(message)
    await env.down()
  })
})
```

**PS**
I've also noticed that running the working test (`bazel test //gateway:test_works`) is not being cached. Why?

**Comment by mattem** [comment] 2021-02-06 18:59
Running the repro, both tests fail for me:

```
yarn test
yarn run v1.13.0
$ yarn bazelisk test //... --test_output=all
$ /Users/matt/Documents/workspace/scratch/bazel-testcontainers-repro/node_modules/.bin/bazelisk test //... --test_output=all
Starting local Bazel server and connecting to it...
INFO: Analyzed 7 targets (239 packages loaded, 3606 targets configured).
INFO: Found 5 targets and 2 test targets...
FAIL: //gateway:test_fails (see /private/var/tmp/_bazel_matt/0869858986c8b9afdaf1b163050570fc/execroot/bazel_testcontainers_repro/bazel-out/darwin-fastbuild/testlogs/gateway/test_fails/test.log)
INFO: From Testing //gateway:test_fails:
==================== Test output for //gateway:test_fails:
Randomized with seed 78085
Started
F

Failures:
1) integration test starts gateway with port
  Message:
    Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
  Stack:
    Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
        at <Jasmine>
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)

1 spec, 1 failure
Finished in 10.006 seconds
Randomized with seed 78085 (jasmine --random=true --seed=78085)
================================================================================
FAIL: //gateway:test_works (see /private/var/tmp/_bazel_matt/0869858986c8b9afdaf1b163050570fc/execroot/bazel_testcontainers_repro/bazel-out/darwin-fastbuild/testlogs/gateway/test_works/test.log)
INFO: From Testing //gateway:test_works:
==================== Test output for //gateway:test_works:
Randomized with seed 32267
Started
F

Failures:
1) integration test starts gateway without port
  Message:
    Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
  Stack:
    Error: Timeout - Async function did not complete within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
        at <Jasmine>
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7)

1 spec, 1 failure
Finished in 10.008 seconds
Randomized with seed 32267 (jasmine --random=true --seed=32267)
================================================================================
INFO: Elapsed time: 49.117s, Critical Path: 15.83s
INFO: 29 processes: 24 internal, 2 darwin-sandbox, 3 worker.
INFO: Build completed, 2 tests FAILED, 29 total actions
//gateway:test_fails                                                     FAILED in 10.4s
  /private/var/tmp/_bazel_matt/0869858986c8b9afdaf1b163050570fc/execroot/bazel_testcontainers_repro/bazel-out/darwin-fastbuild/testlogs/gateway/test_fails/test.log
//gateway:test_works                                                     FAILED in 10.3s
  /private/var/tmp/_bazel_matt/0869858986c8b9afdaf1b163050570fc/execroot/bazel_testcontainers_repro/bazel-out/darwin-fastbuild/testlogs/gateway/test_works/test.log

INFO: Build completed, 2 tests FAILED, 29 total actions
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by flolu** [comment] 2021-02-10 18:39
@mattem The reason might be, that the containers need to be downloaded the first time you run the tests. I've increased the timeout.

Would be great if you could pull the latest commit and try again.

**Comment by mattem** [comment] 2021-02-11 15:38
Thanks, I can repro now. 

So neither of these tests are really passing under bazel. The issue is that because the `docker-compose up` is happening in the runfiles tree of the test, so the bind mounts fail (docker doesn't follow symlinks) and the container exits instantly. You can see this effect by `cd`'ing in to the runfiles tree and running the same (more or less) command as testcontainers is doing:

```
docker-compose -f docker-compose.fails.yaml up

Creating repro_gateway-fails ... done
Attaching to repro_gateway-fails
repro_gateway-fails | yarn run v1.22.5
repro_gateway-fails | Error: EISDIR: illegal operation on a directory, read
repro_gateway-fails |     at Object.readSync (fs.js:592:3)
repro_gateway-fails |     at tryReadSync (fs.js:366:20)
repro_gateway-fails |     at Object.readFileSync (fs.js:403:19)
repro_gateway-fails |     at onUnexpectedError (/opt/yarn-v1.22.5/lib/cli.js:92554:106)
repro_gateway-fails |     at /opt/yarn-v1.22.5/lib/cli.js:92673:9
repro_gateway-fails exited with code 1
```

Both compose files fail this way. What I can only imagine is the `port` binding is taking longer, so the container is returned as running before it exists? Not sure.

If the `command` is set to the following to create a simple http-server that can return the message, the test_fails now passes and shows that the port binding is working as expected:

```
command: node -e "require('http').createServer((req,res) => {res.write('server is running\n'); res.end();}).listen(3000)"
```

**Comment by flolu** [comment] 2021-02-13 20:45
@mattem Thank you for finding the underlying issue!

I guess there is not much I can do about it since Docker does not support symlinked volumes, right?

Is there any way I could use [rules_docker](https://github.com/bazelbuild/rules_docker) to build images for those services to pass their names into some dynamically generated `docker-compse.yaml` file?

**Comment by mattem** [comment] 2021-02-16 15:13
You could build the container with rules_docker, but somewhere you'd have to import that built image before the test runs, perhaps testcontainers has a method for this, as as far as I know, docker-compose doesn't accept a `.tar` for the image.

You might also want to take a look at [container_test](https://github.com/bazelbuild/rules_docker/blob/master/contrib/test.bzl) for testing the container.

I'm going to close this issue as I think everything is working as expected. If you need further assistance, perhaps reach out on [Bazel Slack](https://slack.bazel.build/)

**Closed by mattem** 2021-02-16 15:13 UTC
Labels: question/docs
