### ISSUE TITLE
Changing module_name on ts_library requires clean

### ISSUE THREAD

**Issue by mattem** [bazelbuild/rules_nodejs#1561] opened 2020-01-19 00:03 UTC
# 🐞 bug report

### Affected Rule

ts_library

### Is this a regression?
Maybe?

### Description
Running a build on a ts_library label that previously didn't have a `module_name` attr defined requires the user to run `bazel clean`

## 🔬 Minimal Reproduction
`BUILD`
```
load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "example",
    srcs = ["example.ts"],
    tsconfig = "//:tsconfig",
    #module_name = "@evertz/foo"
)
```

`example.ts`
```
export const FOO = 'FOO';
```

Run a build on `example`, completes successfully as expected.
Remove the comment on the `module_name` attr and rerun the build, error as shown below
Run `bazel clean` and rerun the build, completes successfully

## 🔥 Exception or Error

<pre><code>
matt@Matts-MacBook-Pro $ bzl build //tools/example
INFO: Analyzed target //tools/example:example (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
ERROR: /Users/matt/Documents/workspace/bazel/bzlgen/tools/example/BUILD:3:1: Compiling TypeScript (devmode) //tools/example:example failed (Exit 1)
Compilation failed Error: ERROR: /private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/tools/example/example.ts contains a module name declaration bzlgen/tools/example/example which would be overwritten with @evertz/foo/example by Bazel's TypeScript compiler.
    at perfTrace.wrap (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/compiler_host.js:384:31)
    at Object.wrap (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/perf_trace.js:44:20)
    at CompilerHost.getSourceFile (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/@bazel/typescript/internal/tsc_wrapped/compiler_host.js:375:30)
    at findSourceFile (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:92852:29)
    at /private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:92751:85
    at getSourceFileFromReferenceWorker (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:92718:34)
    at processSourceFile (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:92751:13)
    at processRootFile (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:92581:13)
    at /private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:91597:60
    at Object.forEach (/private/var/tmp/_bazel_matt/6a6dbffc4433d3831f9de5afc4554667/execroot/bzlgen/bazel-out/host/bin/external/npm/@bazel/typescript/bin/tsc_wrapped.sh.runfiles/npm/node_modules/typescript/lib/typescript.js:288:30)
Target //tools/example:example failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.499s, Critical Path: 0.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 2.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 19 12:33:30 2019 (1576758810)
Build timestamp: 1576758810
Build timestamp as int: 1576758810
  </code>
</pre>

**Rules_nodejs version:**

<pre>
  <code>
1.1.0
  </code>
</pre>

**Comment by marcus-sa** [comment] 2020-01-19 11:03
A workaround instead of running `bazel clean` is to delete the generated files from `ts_library`

**Comment by joeljeske** [comment] 2020-02-19 21:56
Fun fact, it appears that `bazel shutdown` fixes the issue too. I wonder if its kept in internal state?

**Comment by mrmeku** [comment] 2020-02-28 00:10
I've confirmed that this only occurs when building typescript using the worker mode. To "fix" the bug we might just want to update the error message to suggest trying the same build with `--strategy=TypeScriptCompile=sandboxed`

**Comment by joeljeske** [comment] 2020-02-28 00:12
Oh that makes more sense why a shutdown of bazel would fix it. 

Perhaps then it is a bug in the worker state that could be fixed. @alexeagle does this sound like expected behavior or a bug?

**Comment by mrmeku** [comment] 2020-02-28 00:20
Or maybe we could remove the check all together. We are in a scenario where the file meta data is loaded from a cache. That cached metadata has the module name from the previous build. I think that perhaps we could get away with just overwriting the old module name without consequence. But maybe only once per compilation

**Comment by joeljeske** [comment] 2020-02-28 00:54
That’s an interesting setup. Could you explain more about what you are doing?

**Comment by joeljeske** [comment] 2020-02-28 13:05
Ok so looking at the src, it appears the error is thrown to guard against a source file having a module name that would conflict with the module name set via bazel. 

https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/compiler_host.ts#L461

It would seem that where the module name is set, that we need to also track that it is a generated module name, not one set in source. This would allow us to change the module name in the future while still knowing that we are not overriding a module name from the source code. 

I can put up a PR to rules typescript if @alexeagle or @gregmagolan agrees with my assessment.

**Comment by zhuhaow** [comment] 2020-07-02 07:32
Any progress on this?

**Comment by alexeagle** [comment] 2020-07-05 17:08
This is definitely a bug, has bothered me from when I first added the AMD module naming scheme to emulate Closure's `goog.module` and I never tracked it down. Something non-hermetic is going on in the worker mode. @joeljeske suggestion seems like a pretty good workaround, works for me but you'll need to find someone at Google to merge the rules_typescript PR.

**Comment by mattem** [comment] 2020-12-03 14:00
Reopening as this is still a bug, and now easier to fix with rules_typescript inside this repo

**Comment by alexeagle** [comment] 2020-12-03 15:08
And I hit it yesterday 🙄

**Comment by tomasdev** [comment] 2020-12-22 02:04
+1 🙄

**Comment by tayles** [comment] 2021-01-22 04:26
Also just hit this in bazel 3.3.1 / rules_nodejs 2.0.2. Can confirm `bazel shutdown` is the quickest workaround. (👋🏻 hi @mattem!)

**Comment by fmeum** [comment] 2021-04-27 14:15
This is still an issue with Bazel 3.7.0 and rules_nodejs 3.4.1. Still fixed by `bazel shutdown`. If a full fix would require too much effort, adding a suggestion to run `bazel shutdown` to the error message would already be of help.

**Closed** 2023-07-14 23:10 UTC
Labels: bug
