### ISSUE TITLE
bazel run @yarn//:yarn uses system node instead of nodejs target

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_nodejs#7] opened 2017-09-06 19:31 UTC
This means that rules_nodejs requires node to be installed on the system before it is able to do anything.

```
$ bazel run @yarn//:yarn
INFO: Analysed target @yarn//:yarn (6 packages loaded).
INFO: Found 1 target...
Target @yarn//:yarn.sh up-to-date (nothing to build)
INFO: Elapsed time: 7.735s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: [redacted]/a3cee343d71b0f2101c79d88
606a48aa/external/yarn/yarn.sh
yarn install v0.22.0
warning example@0.0.1: License should be a valid SPDX license expression
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@angular/bazel@5.0.0-beta.5-4ec5e28" has incorrect peer dependency "@angular/compiler-cli@5.0.0-be
ta.5-4ec5e28".
[4/4] Building fresh packages...
$ ngc -p angular.tsconfig.json
/usr/bin/env: node: No such file or directory
error Command failed with exit code 127.
```

It may be be possible to invoke ngc's index.js from the included nodejs and not have this problem but by invoking it directly it uses the /usr/bin/env node shebang.

**Comment by alexeagle** [comment] 2017-09-07 02:05
Ah, the problem isn't `@yarn//:yarn` itself, it's the command in the `package.json#postinstall` in the `angular-bazel-example` repo. `ngc` is a shorthand for the binary in the `@angular/bazel`package. I think we can't use that shorthand.

**Comment by alexeagle** [comment] 2017-09-08 15:51
Seems like we should correctly set the `PATH` environment variable so that all nodejs programs started under bazel can just start with `#!/usr/bin/env node` and get the node we installed.

**Comment by achew22** [comment] 2017-09-08 16:58
The other option would be to invoke the command as a direct call to node
with the first argument of the path to the js file. Manipulating the path
is a good strategy for Linux and Darwin, but I don't know how that would
work for Windows which I believe is a must have given our previous
conversations.

**Comment by alexeagle** [comment] 2017-09-08 17:50
We shouldn't make a special case for our `postinstall` command - users could call anything in their `package.json` and expect that to work.

**Comment by alexeagle** [comment] 2017-09-14 20:25
@ocombe can I assign to you?

**Comment by ocombe** [comment] 2017-09-14 20:35
ok, I'm not sure what to do so I hope that you're in no rush

**Comment by alexeagle** [comment] 2018-03-06 18:20
@gregmagolan is this fixed?

**Comment by gregmagolan** [comment] 2018-03-09 18:04
> @gregmagolan is this fixed?

Yes. No system node is needed anymore.

**Closed by gregmagolan** 2018-03-09 18:04 UTC
Labels: bug, help wanted

**Comment by ptarjan** [comment] 2022-02-10 17:52
I'm still seeing this problem

```
$ bazel run @yarn//:yarn_bin
INFO: Invocation ID: 104db8b3-ada8-41bf-9629-d63468fe76a6
INFO: Analyzed target @yarn//:yarn_bin (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @yarn//:bin/yarnpkg/bin/yarn.js up-to-date (nothing to build)
INFO: Elapsed time: 0.253s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
yarn install v1.22.10
$ ./preinstall_legacy.sh
building file list ... done
./
config/

sent 308 bytes  received 74 bytes  764.00 bytes/sec
total size is 15434  speedup is 40.40
building file list ... done
./
rules/

sent 349 bytes  received 80 bytes  858.00 bytes/sec
total size is 12237  speedup is 28.52
warning Resolution field "5.0.0rc0" has an invalid version entry and may be ignored
[1/5] 🔍  Validating package.json...
warning Resolution field "5.0.0rc0" has an invalid version entry and may be ignored
error rh@: The engine "node" is incompatible with this module. Expected version "^16.11.0". Got "17.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
