### ISSUE TITLE
Allow .zip or directory for TypeScript sources

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#2030] opened 2020-07-11 17:23 UTC
# 🚀 feature request

### Relevant Rules

ts_library

### Description

I want to compile generated typescript files. That typically means allowing a variable number of source TS files.

### Describe the solution you'd like

Allow directories as a source.

For comparison, java_library accepts .srcjar files (ZIP archives of sources) for exactly this purpose. 

### Describe alternatives you've considered

Ad-hoc scripts.

**Comment by alexeagle** [comment] 2020-07-13 15:42
yup. we should have this, it's a dupe of #1907

**Closed by alexeagle** 2020-07-13 15:42 UTC
