### ISSUE TITLE
Can't forward the runfiles directory to nodejs_binary if its used as a subtool

### ISSUE THREAD

**Issue by a-ignatov-parc** [bazelbuild/rules_nodejs#1910] opened 2020-05-25 21:45 UTC
# 🐞 bug report

### Affected Rule

The issue is caused by the rule: `nodejs_binary`

### Is this a regression?

Hard to say. The problem exist for a long time. Based on [this](https://github.com/bazelbuild/rules_nodejs/pull/587) PR, and [reported repo](https://github.com/Globegitter/rules_nodejs_sh_wrapper_repro) this issue exist since `0.27.8`.

### Description

Bazel has [a documented way](https://docs.bazel.build/versions/master/skylark/rules.html#tools-depending-on-tools) to create and use tools with runfiles that are based on other tools with their own runfiles.

The idea is simple:
1. The root tool collects and merge its subtools runfiles.
2. Each subtool should accept runfiles root as a parameter through environment or command line argument.

Unfortunately, there is no legit way to explicitly configure runfiles for `nodejs_binary`, which leads to non-deterministic execution, since `node_launcher.sh` is trying to resolve its runfiles based on heuristics described [here](https://github.com/bazelbuild/rules_nodejs/blob/8509d9c3b3a9d7558fea98f23f12da9743dc3288/internal/node/launcher.sh#L31).

`RUNFILES_DIR` seems to be the most suitable for solution, however `node_launcher.sh` has [a comment](https://github.com/bazelbuild/rules_nodejs/blob/8509d9c3b3a9d7558fea98f23f12da9743dc3288/internal/node/launcher.sh#L28) that searching for runfiles in this directory is not always correct. Sadly, I could not find any details about this.

If there are serious concerns about using `RUNFILES_DIR` we can use the [java binary approach](https://github.com/bazelbuild/bazel/blob/fd5d29aa4ef907a15ec6db0e359e86df1acf64fc/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L148) with a standalone env variable, which can be explicitly configured externally.

## 🔬 Minimal Reproduction

1. Checkout https://github.com/a-ignatov-parc/bazel-demo/
1. Switch to `runfiles-problem` branch.
1. Run `./bazel clean`.
1. Run `./bazel run //app:runner`. Works as expected.
1. Switch to `runfiles-problem-2` branch.
1. Run `./bazel run //app:runner` again. Works as expected.
1. Switch back to `runfiles-problem` branch.
1. Run `./bazel build //app/...`
1. Run `./bazel run //app:runner`. Still works.
1. Switch again to `runfiles-problem-2` branch.
1. Try to run `./bazel run //app:runner`. Will fail because `chalk` module will be resolved in `app.sh.runfiles` which are not rebuild since `//app:runner` is a different target.
1. Switch to `runfiles-problem-3` branch.
1. Run `./bazel run //app:runner`. It will work because root tool was able to forward runfiles to subtool with defining `TEST_SRCDIR`, which is a workaround in this situation.

## 🔥 Exception or Error

<pre><code>
[app_require_patch.js] patching require for //app:app
  cwd: /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/runner.runfiles/bazel_demo
  RUNFILES: /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles
  TARGET: //app:app
  BIN_DIR: bazel-out/darwin-fastbuild/bin
  GEN_DIR: bazel-out/darwin-fastbuild/bin
  INSTALL_SOURCE_MAP_SUPPORT: true
  MODULE_ROOTS: [
  {
    "module_name": {},
    "module_root": "bazel_demo/app"
  }
]
  NODE_MODULES_ROOT: npm/node_modules
  USER_WORKSPACE_NAME: bazel_demo

[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
[app_require_patch.js] resolved file /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
[app_require_patch.js] resolved bazel_demo/app/index.js within runfiles to /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js from undefined
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello
[app_require_patch.js] resolved file /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/chalk
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/npm/node_modules/chalk
Error: Cannot find module 'chalk'. Please verify that the package.json has a valid "main" entry
required in target //app:app by '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello.js'
  looked in:
    built-in, relative, absolute, nested node_modules - Error: Not a built-in module, relative or absolute import
    runfiles - Error: Cannot find module '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/chalk'
Require stack:
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello.js
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
-
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/npm/node_modules/chalk'
Require stack:
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello.js
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
-

    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/runner.runfiles/bazel_demo/app/app_require_patch.js:482:17)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at app/hello.ts:1:1
    at /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello.js:6:17
    at Object.<anonymous> (/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX 10.15.4
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 1.2.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 26 15:27:31 2019 (1574782051)
Build timestamp: 1574782051
Build timestamp as int: 1574782051
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.6.1
  </code>
</pre>

**Anything else relevant?**

**Comment by alexeagle** [comment] 2020-05-26 14:15
Wow, that is complicated! Thanks for the detailed report and repro.
Just for background, the runfiles handling is currently messy, and changes there tend to be brittle and very slow to debug. We've also been considering not putting node_modules into runfiles at all, because Bazel wants to symlink every individual file there. Instead we have our "linker" which just does one symlink per package, and we expect that's a lot faster than the runfiles setup step we have now.
I suspect we should get further with that investigation before we try to find time to dive into this.

**Comment by a-ignatov-parc** [comment] 2020-05-28 09:07
> Instead we have our "linker" which just does one symlink per package, and we expect that's a lot faster than the runfiles setup step we have now.

It looks like this should work for `node_modules` 👍

However, it seems that the problem will exist for other cases, such as using files from the `data` attribute and external repos.

I'll double-check these cases a little later and post an update here with repro if I'll be able to confirm them.

**Comment by a-ignatov-parc** [comment] 2020-06-01 20:43
@alexeagle I spent some time and realized that the problem can be easily reproduced even with the application source code, simply by renaming the files.

Here is a repro case:
1. Checkout https://github.com/a-ignatov-parc/bazel-demo/
1. Switch to `runfiles-problem` branch.
1. Run `./bazel clean` to reset the environment.
1. Run `./bazel run //app:runner`. Works as expected.
1. Switch to `runfiles-problem-4` branch. 
1. Run `./bazel run //app:runner` again. Works as expected.
1. Switch back to `runfiles-problem` branch.
1. Run `./bazel build //app/...`. This will create a standalone `runfiles` for the original `nodejs_binary`.
1. Run `./bazel run //app:runner`. Still works.
1. Switch back to `runfiles-problem-4` branch.
1. Run `./bazel run //app:runner`. We will see an exception due to the inability to resolve renamed module in the `runfiles` of the original `nodejs_binary` that is used as a subtool. It's because bazel didn't update them since we executed a different target.

```
[app_require_patch.js] patching require for //app:app
  cwd: /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/runner.runfiles/bazel_demo
  RUNFILES: /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles
  TARGET: //app:app
  BIN_DIR: bazel-out/darwin-fastbuild/bin
  GEN_DIR: bazel-out/darwin-fastbuild/bin
  INSTALL_SOURCE_MAP_SUPPORT: true
  MODULE_ROOTS: [
  {
    "module_name": {},
    "module_root": "bazel_demo/app"
  }
]
  NODE_MODULES_ROOT: npm/node_modules
  USER_WORKSPACE_NAME: bazel_demo

[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
[app_require_patch.js] resolved file /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
[app_require_patch.js] resolved bazel_demo/app/index.js within runfiles to /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js from undefined
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello-2
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello-2
[app_require_patch.js] try to resolve in runfiles /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/npm/node_modules/bazel_demo/app/hello-2
Error: Cannot find module 'bazel_demo/app/hello-2'. Please verify that the package.json has a valid "main" entry
required in target //app:app by '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js'
  looked in:
    module root bazel_demo/app/hello-2 - No file bazel_demo/app/hello-2 found in module root bazel_demo/app/hello-2
    built-in, relative, absolute, nested node_modules - Error: Cannot find module 'bazel_demo/app/hello-2'
Require stack:
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
-
    runfiles - Error: Cannot find module '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/hello-2'
Require stack:
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
-
    node_modules attribute (npm/node_modules) - Error: Cannot find module '/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/npm/node_modules/bazel_demo/app/hello-2'
Require stack:
- /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js
-

    at Function.module.constructor._resolveFilename (/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/runner.runfiles/bazel_demo/app/app_require_patch.js:482:17)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at app/index.ts:1:1
    at /private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js:6:17
    at Object.<anonymous> (/private/var/tmp/_bazel_antonignatov/3265d92628b35713e12ecf4e9194b9a6/execroot/bazel_demo/bazel-out/darwin-fastbuild/bin/app/app.sh.runfiles/bazel_demo/app/index.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

And, as expected, the workaround with forwarding `runfiles` via `TEST_SRCDIR` fixed the problem. This can be verified by switching to `runfiles-problem-5` and running `./bazel run //app:runner` right after the step `#11`.

As far as I can tell, the linker will not solve this problem, and we should follow the recommendations of the bazel team to accept `runfiles' as a parameter.

**Comment by samschlegel** [comment] 2020-07-08 02:26
Curious what issues had been run into with `RUNFILES_DIR`, as we use that extensively in our code base with none nodejs stuff. In the launcher `runfiles_export_envvars` isn't being called so any subprocesses that are run that need to find the right `RUNFILES_DIR` will fail. Possibly that's the issue that had been seen?

**Comment by alexeagle** [comment] 2020-07-08 14:37
RUNFILES_DIR doesn't work with programs that don't use a runfiles helper library. Basically the whole runfiles concept assumes you'll only use Bazel-aware programs in your build, which to me seems like a non-starter. Bazel could have made runfiles concept optional or not even had such a thing - if you want to run a program in the output tree, you can copy/symlink files from the sources to that directory.
But I think we're stuck supporting both runfiles and linker mechanisms anyway. Not sure when anyone will have time to dig into this...

**Comment by samschlegel** [comment] 2020-07-08 18:43
I was more referring to why there's a whole separate `RUNFILES` environment variable in the launcher with the comment "Find our runfiles as ${PWD}/${RUNFILES_DIR} is not always correct.", since it seems to be doing mostly the same things.

I ask because the issue here is that the runfiles resolution is wrong. You can see that the RUNFILES is being resolved to `bazel-out/k8-fastbuild/bin/app/runner.runfiles/bazel_demo/app/app.sh.runfiles` when it should be resolved to the runner's at `bazel-out/k8-fastbuild/bin/app/runner.runfiles/bazel_demo/app/runner.runfiles`. `RUNFILES_DIR` solved this correctly.

Because it's resolving to the wrong runfiles directory, the runfiles can become out of date, which is what's happening in @a-ignatov-parc's reproduction. The `bazel-out/k8-fastbuild/bin/app/runner.runfiles/bazel_demo/app/app.sh.runfiles` directory was only built by the `bazel build //app/...`, so its symlinks go out of date when the file is renamed.

`runner.runfiles` is strictly a superset of `app.sh.runfiles` and that should always be the case, so that should be the only runfiles directory used. If that's not the case, then the rule implementation that's calling app.sh is implemented wrong and isn't including transitive files, so the fix should be there.

**Comment by samschlegel** [comment] 2020-07-08 18:58
As far as I can tell replacing the whole RUNFILES segment with the following works for me. Had to extract the released .tar.gz and modify there as I couldn't get `git_repository` to work.

```bash
runfiles_export_envvars
export RUNFILES=$(readlink -f ${RUNFILES_DIR})
```

**Closed** 2020-09-22 01:33 UTC
Labels: Can Close?, bug, package:builtin

**Comment by samschlegel** [comment] 2020-09-23 16:17
This is still an issue. Not sure how to reopen
