### ISSUE TITLE
Angular devs should be able to use RBE from Mac

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1038] opened 2019-08-20 21:45 UTC
Current theory is that karma is set to cfg=target but should be cfg=host

**Comment by alexeagle** [comment] 2019-08-20 21:46
We should also ensure that remote cache hits work for Mac clients

**Comment by pauldraper** [comment] 2019-09-02 19:53
I figured Bazel just doesn't support cross platform caching.

Or else the Java rules would have already been fixed https://github.com/bazelbuild/bazel/issues/4714

**Comment by alexeagle** [comment] 2019-09-11 21:57
Yes, but in theory there are no platform-dependencies in our JS files so we could probably share a cache.
even if we didn't though, we'd want our mac actions to run on RBE and share a cache with other mac actions.

**Comment by joeljeske** [comment] 2020-02-20 12:25
Would the platform dependent node binary participate in the action hash? Is this a scenario that would require building node from source?

I am very interested is sharing cache hits cross platform. Has any more thoughts or planning occurred about this? Is there any assistance I could provide? 

My alternatives of this being supported directly In bazel seem to be:

1. Duplicate CI Jobs on all platforms to populate the remote cache
2. Setup a different remote per platform and allow all devs to populate the cache for their platform

**Comment by kylecordes** [comment] 2020-02-25 14:57
Maybe there will be a future Bazel version N in which the platform is no longer an implicit dependency of everything, but rather only becomes a dependency when relying on a piece of tooling marked as depending on the platform. It seems like that would be the general solution to this and similar issues.

I don't see how this could reasonably be done within the scope of rules_nodejs though?

**Comment by joeljeske** [comment] 2020-02-26 12:52
@kylecordes I would tend to agree. I’m somewhat new to bazel but became hopeful when @alexeagle opened this ticket and mentioned it might be possible without major changes to bazel core.

**Comment by gregmagolan** [comment] 2020-03-24 14:37
Although a bit hacky, this was fixed a little while ago for the angular repo.

RBE works from mac but it requires settings `--cpu=k8` and `--host_cpu=k8` to work. For example,

```
yarn test-non-ivy ... --config=remote --google_credentials=/path/to/gcp_rbe.json --cpu=k8 --host_cpu=k8
```

**Closed by gregmagolan** 2020-03-24 14:37 UTC
Labels: need: repro steps

**Comment by joeljeske** [comment] 2020-03-24 15:01
Can we reopen this for other projects then besides the angular repo? My understanding is that those flags are global, so if I have any non nodejs rules as part of that build, it would fail to build those as the host config would be incorrect, right? This seems to leak the implementation limitations to each dev.

**Comment by gregmagolan** [comment] 2020-03-24 15:09
Yes. It is quite broken in bazel toolchain outside of rules_nodejs. The `--cpu=k8` `--host_cpu=k8` is to get around that issue and not anything in rules_nodejs in particular. AFIACT the fix to remove those flags is in the bazel toolchain definitions to add OSX support.

**Comment by gregmagolan** [comment] 2020-03-24 15:10
Although I do agree that it would be ideal to have cross-platform RBE working in the general case as those flags are global as you say.

**Comment by joeljeske** [comment] 2020-03-24 15:12
Thanks for the info. Are you aware of a current open ticket in Bazel itself for this behavior?

**Comment by gregmagolan** [comment] 2020-03-24 15:20
Well would look at that.
I tried to tease out the error I observed before on the angular repo without those flags and with bazel 2.1.1 and bazel_toolchains 2.1.1 it seems it has been fixed as the build is running.
Running `yarn test-non-ivy ... --config=remote --google_credentials=/Users/greg/gcp_rbe.json` appears to work.

**Comment by gregmagolan** [comment] 2020-03-24 15:46
Confirmed by @josephperrott. No more `--cpu=k8 --host_cpu=k8` when using bazel 2.1.1.

**Comment by joeljeske** [comment] 2020-03-24 16:23
It looks like config remote configures k8 in the bazel rc. Try without that?

**Comment by gregmagolan** [comment] 2020-03-25 01:55
> It looks like config remote configures k8 in the bazel rc. Try without that?

Err. Yes. You are correct. I didn't notice that change. I teased out the error this time which still happens on the angular repo with Bazel 2.1.1 & bazel_toolchains 2.1.1:

```
ERROR: /private/var/tmp/_bazel_greg/5e8f8a9cd1c6fbc1afd11e37ee1fe2e5/external/bazel_toolchains/configs/ubuntu16_04_clang/10.0.0/bazel_2.1.1/cc/BUILD:50:1: in cc_toolchain_suite rule @bazel_toolchains//configs/ubuntu16_04_clang/10.0.0/bazel_2.1.1/cc:toolchain: cc_toolchain_suite '@bazel_toolchains//configs/ubuntu16_04_clang/10.0.0/bazel_2.1.1/cc:toolchain' does not contain a toolchain for cpu 'darwin'
ERROR: Analysis of target '//packages/examples/upgrade/static/ts/lite-multi-shared:devserver' failed; build aborted: Analysis of target '@bazel_toolchains//configs/ubuntu16_04_clang/10.0.0/bazel_2.1.1/cc:toolchain' failed; build aborted
```

**Comment by gregmagolan** [comment] 2020-03-25 01:58
I couldn't find any outstanding issues in the Bazel repo for this
