### ISSUE TITLE
Linker should not have expectations about cwd format.

### ISSUE THREAD

**Issue by greenboxal** [bazelbuild/rules_nodejs#2035] opened 2020-07-13 20:29 UTC
# 🐞 bug report

### Affected Rule

`nodejs_binary`/`nodejs_container`

### Is this a regression?

Yes, on 1.x.

### Description

`rules_docker` breaks as there's no `bazel-out` on cwd, even though it's inside a Runfiles compatible tree.

## 🔬 Minimal Reproduction

Use `https://github.com/bazelbuild/rules_docker/blob/master/nodejs/nodejs.bzl` with any Javascript input using 2.0.

## 🔥 Exception or Error

<pre><code>
  No 'bazel-out' folder found in path '/app/security/auth-frontend/auth-frontend-docker.binary.runfiles/brex'!

    at panic (/app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:23:11)
    at /app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:129:13
    at Generator.next (<anonymous>)
    at /app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:4:12)
    at resolveRoot (/app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:123:12)
    at /app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:398:31
    at Generator.next (<anonymous>)
    at /app/security/auth-frontend/auth-frontend-docker.binary.runfiles/build_bazel_rules_nodejs/internal/linker/index.js:8:71
</code></pre>

## 🌍  Your Environment

**Output of `bazel version`:**

<pre>
  <code>
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
    http_archive(
        name = "build_bazel_rules_nodejs",
        sha256 = "cb6d92c93a1769205d6573c21363bdbdcf5831af114a7fbc3f800b8598207dee",
        urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/2.0.0-rc.2/rules_nodejs-2.0.0-rc.2.tar.gz"],
    )
  </code>
</pre>

**Anything else relevant?**
The linker should not expect any path structure regarding what's before `bazel-out` as the runfile structure should be hermetic.

**Comment by alexeagle** [comment] 2020-07-13 22:03
I think it's a dupe of #2002  that also is about linker expecting `$pwd/bazel-out` to exist

**Comment by gregmagolan** [comment] 2020-07-15 07:35
Yes, the root cause is the same as #2002. I can reproduce this in rules_nodejs with the existing rules_docker targets in examples/nestjs & examples/angular. The missing coverage was running the nodejs_image which we are not doing in CI. I will add the missing coverage along with the fix.

**Comment by alexeagle** [comment] 2020-07-15 15:09
Closing as dupe

**Closed by alexeagle** 2020-07-15 15:09 UTC
