### ISSUE TITLE
rules_typescript transitive dependencies set is greater than necessary?

### ISSUE THREAD

**Issue by nickhs** [bazelbuild/rules_nodejs#1752] opened 2020-03-28 16:04 UTC
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library

### Is this a regression?

Not AFAICT

### Description
ts_library deps also transitively includes all of it's deps dependencies - regardless of whether they're needed or not?

For example in [https://github.com/nickhs/rules-typescript-repro](https://github.com/nickhs/rules-typescript-repro) when changing `avatar.ts` (e.g. add something to [Avatar.Size](https://github.com/nickhs/rules-typescript-repro/blob/master/src/avatar/avatar.ts#L1) it leads to rebuilds in:

- avatar_cell (which is expected, it explicitly depends on //src/avatar's avatar.d.ts output)
- grid_row (no explicit dependency, but the avatar.d.ts is required for compilation, so correct)
- **grid** (should not rebuild since grid_row.d.ts hasn't changed?)

It looks like the spurious grid rebuild is pretty quick since the stateful tsc is able to determine that nothing matters has changed? How does memory pressure affect that?

Also how does this affect remote caching? Wouldn't avatar.d.ts be treated as a (spurious implicit) input to grid causing at least a cache check? (and then a cache miss and cache upload?)

The concern here being for larger projects, packages near the top of the build graph will have accumulated large numbers of (probably unecessary) dependencies?

## 🔬 Minimal Reproduction

1) Check out [https://github.com/nickhs/rules-typescript-repro](https://github.com/nickhs/rules-typescript-repro)
2) Modify avatar.ts by adding a new option to Avatar.Size
3) Observe packages being rebuilt via `bzl build -s`

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
MacOS
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
2.0.0.0
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>
1.4.1
  </code>
</pre>

**Anything else relevant?**
I think this is really a fundamental Bazel limitation, rather than specific to rules_typescript. I don't quite follow how rules_typescript can remain performant?

**Comment by alexeagle** [comment] 2020-03-29 01:32
Typescript's type-checker will want to resolve references in the direct dependency `.d.ts` which can be symbols defined in the transitive .d.ts. So it's necessary in general for the entire transitive dependency's typings to be passed to a compilation.

We've always talked about doing some kind of pruning. In theory you could have an action that runs something like the API extractor https://api-extractor.com/pages/setup/configure_rollup/ to create a "rollup" of the transitive .d.ts files and use unreachable code detection, so that the minimal typings flow downstream to dependencies. However that would add more time to produce, so only a benefit in some cases.

You could also use the `--skipLibCheck` flag to TypeScript so that you don't care about whether the direct dependency .d.ts is correct - but I think there may still be cases where the transitive typings are needed to get correct inference for the code being compiled?

In any case as you observed it hasn't been enough of a performance penalty that it was ever solved while I was at Google so I don't think anyone will put in the effort.

**Comment by nickhs** [comment] 2020-03-29 03:46
> Typescript's type-checker will want to resolve references in the direct dependency .d.ts which can be symbols defined in the transitive .d.ts.

Right, absolutely.

> So it's necessary in general for the entire transitive dependency's typings to be passed to a compilation.

Well only a subset may actually be required, but you won't know that until compilation is complete by examining the `.d.ts`?

> We've always talked about doing some kind of pruning. In theory you could have an action that runs something like the API extractor https://api-extractor.com/pages/setup/configure_rollup/ to create a "rollup" of the transitive .d.ts files and use unreachable code detection, so that the minimal typings flow downstream to dependencies. However that would add more time to produce, so only a benefit in some cases.

How would that affect the stateful compiler? Looking at the code it seems like it's very file hash based, by sticking everything into a single `.d.ts` you'd be trashing that file hash every time? Would the stateful compiler/underlying tsc process still be able to re-use program structures etc?

> You could also use the --skipLibCheck flag to TypeScript so that you don't care about whether the direct dependency .d.ts is correct - but I think there may still be cases where the transitive typings are needed to get correct inference for the code being compiled?

That sounds super dangerous. How would the compiler know the types of the required transitive dependencies then? (e.g. in this specific repro `grid_row` wouldn't know the definition of `avatar_cell.props#size` I believe - I guess this is the case you're referring to.)

> In any case as you observed it hasn't been enough of a performance penalty that it was ever solved while I was at Google so I don't think anyone will put in the effort.

I'm pretty surprised by that. I would've thought for any decently deep build graph (> 5 packages) you'd end up collecting a bunch of unnecessary dependencies? Doesn't this also aggressively harm remote cache performance (the scenario I mentioned previously)?

**Comment by alexeagle** [comment] 2020-03-29 16:18
The de-optimization is just that a cascading re-check of depth log(N) happens where it could have been only one re-check. It would be interesting to measure the actual impact.

Yeah `--skipLibCheck` is dangerous which is why we never took that approach, but in frontend ecosystem that kind of correctness-for-performance tradeoff is often taken (see `--assumeChangesOnlyAffectDirectDependencies` as another dubious option)

Actually I realized the correct answer here, based on your "Well only a subset may actually be required, but you won't know that until compilation is complete by examining the .d.ts" - yes after an action completes we could tell Bazel that some of the .d.ts files were never read (by instrumenting the TS compilerHost) and therefore that we don't need to re-run this action if only those files changed. That's already requested in https://github.com/bazelbuild/rules_nodejs/issues/968

So I think I'll close this as a dupe of #968 but let me know if that seems wrong.

**Closed by alexeagle** 2020-03-29 16:18 UTC
Labels: package:typescript, question/docs

**Comment by nickhs** [comment] 2020-03-31 15:31
I agree `unused_inputs_list` from #968 would help the local action cache. The docs on `unused_inputs_list` are pretty sparse, but from my reading it appears it does not affect the remote cache?

In our decently sized project I'm seeing plenty of unnecessary files percolate up to the top of the build graph. How does the remote cache remain performant in these cases?

(I'm happy to keep this closed or open, I just want to make I have a strong handle of the performance characteristics here. Happy to contribute some docs if you think it'll be helpful as well).

**Comment by DavidANeil** [comment] 2020-11-13 22:59
You are correct that `unused_inputs_list` does not affect the remote cache.

Currently the best thing a user can do is to lay out their ts_library deps to mirror their actual ts deps as closely as possible.
Otherwise `unused_inputs_list` is the best we can do to trim the action graph.

Anything else (such as [post-analysis actions](https://docs.google.com/document/d/16iogGwUlISoN2WLha2TAaUdpYCjRiVQ2sRQ7--INxkg/edit?usp=sharing)) would require a change to Bazel itself.
