### ISSUE TITLE
Allow multiple `yarn_install`/`npm_install` when explicitly create in WORKSPACE

### ISSUE THREAD

**Issue by josephperrott** [bazelbuild/rules_nodejs#964] opened 2019-08-05 17:39 UTC
### Description

In our repository we have multiple different projects we are building.  Because these projects have different dependencies we have historically had multiple package.json files managing different project's dependencies.  As I am looking to set up bazel build rules for a second project (representing the replacement/update of using the package.json scripts for building), I am running into issues with having multiple node_modules installed

It seems to me that it should be possible to explicitly create multiple `node_modules` when done via multiple `npm_install`/`yarn_install` commands.

cc: @alexeagle

**Comment by alexeagle** [comment] 2019-08-05 18:23
I think we are missing some detail here - it does work fine to have multiple npm_install/yarn_install in the WORKSPACE - but as we discussed a downstream rule can't have `deps` that contains a mix from them. Is that the issue here?

**Comment by josephperrott** [comment] 2019-08-13 14:50
My understanding was that I couldn't mix `node_modules` in a dependency of a single target.  

Since each action/target is executed independently, it shouldn't make a difference that one of the deps was created with a different `node_modules` right?

**Comment by alexeagle** [comment] 2019-09-23 15:59
We can have a tree of `node_modules` directories so that we don't try to flatten/de-dupe in the case of diamond dependencies. It's basically identical to what yarn workspaces does so let's make this a dupe of #266

**Closed by alexeagle** 2019-09-23 15:59 UTC
