### ISSUE TITLE
@bazel/typescript npm package includes external/npm/node_modules folder

### ISSUE THREAD

**Issue by gregmagolan** [bazelbuild/rules_nodejs#1551] opened 2020-01-15 02:00 UTC
See here https://unpkg.com/browse/@bazel/typescript@1.1.0/external/npm/node_modules/

Also apparent here: https://github.com/gregmagolan/rules_nodejs-builds/tree/labs/%40bazel_typescript

**Comment by mattem** [comment] 2020-01-19 00:08
Ah, this seems to be what @kylecordes was describing in #1499.

**Comment by kylecordes** [comment] 2020-01-25 03:12
Wow, it never occurred to me to go look at erroneously included externals from there, rather than a packaging bug, as the cause.

**Comment by alexeagle** [comment] 2020-02-28 22:33
Kyle reported first so I'll close this as dupe of #1499

**Closed by alexeagle** 2020-02-28 22:33 UTC
Labels: bug

**Comment by gregmagolan** [comment] 2020-03-02 16:14
Fixed with https://github.com/bazelbuild/rules_nodejs/commit/808999950d9691c0f191a778d4c2e128ae3e369e
