### ISSUE TITLE
Support optional dependency on stardoc

### ISSUE THREAD

**Issue by joeljeske** [bazelbuild/rules_nodejs#1666] opened 2020-02-24 18:51 UTC
# 🚀 feature request

### Relevant Rules

I would like to be able to rely on `@build_bazel_rules_nodejs//:bzl` so that I can generate my own skydocs that leverage rules_nodejs.

### Description

Currently, the skydoc dependency is mocked out at your deployment time to avoid a mandatory transitive dependency, which I think is good. The problem is that this prevents me from documenting my own rules using skydoc since my rules rely on rules_nodejs. 

It would be nice to somehow support this optionally. 

### Describe the solution you'd like

Someway that I can rely on skydoc for doc generating while still relying on rules_nodejs in my own rules and macros.

### Describe alternatives you've considered

- Patching rules_nodejs to provide this behavior
- Explicitly importing every .bzl inside rules_node to create my own `bzl_library` representing rules_nodejs

**Comment by alexeagle** [comment] 2020-02-28 14:59
Dupe of #1348 will followup there

**Closed by alexeagle** 2020-02-28 14:59 UTC
