### ISSUE TITLE
Support changing working directory in npm_package_bin

### ISSUE THREAD

**Issue by hsyed** [bazelbuild/rules_nodejs#1840] opened 2020-04-21 09:06 UTC
# 🚀 feature request

### Description

I'm trying to build a vue application (details https://github.com/bazelbuild/rules_nodejs/issues/1831). I have had success but the resulting application is not quite correct yet. `npm_package_bin` runs from the root of the workspace however the vue cli tool expects be run in the root of vue project to pick up various build config files and directories.

### Describe the solution you'd like

To get past the problem we need `npm_package_bin` to support changing the working directory to the current package.

**Comment by alexeagle** [comment] 2020-04-24 23:20
We could make this a built-in feature but it's pretty easy to do in userspace.

```
load("@bazel_skylib//rules:write_file.bzl", "write_file")

write_file(
    name = "write_chdir_script",
    out = "chdir.js",
    content = ["process.chdir(__dirname)"],
)

vue-cli-service(
    ...
    args = ["--node_options=--require=./$(execpath chdir.js)"]
)
```

**Comment by alexeagle** [comment] 2020-04-24 23:22
Note that I discussed this with @gregmagolan and the reason we didn't build it in yet is that lots of bazel path support expects "workspace-absolute" paths, so while that code snippet is working for me in a `react-scripts` scenario we need to think through bad interactions it might have

**Comment by weixiao-huang** [comment] 2020-04-25 03:45
this method may hang so much time and due to timeout, you can try my hack method in https://github.com/bazelbuild/rules_nodejs/issues/1776#issuecomment-619313234

**Comment by dubov94** [comment] 2020-04-25 05:04
@weixiao-huang Could you provide a complete minimal (non-)working example? Alex's suggestion looks reasonable to me.

Once again, if you want a module that 'just works' out of the box [here it is](https://npmjs.com/package/vue-cli-launcher#bazel). It's a launcher for `vue-cli-service` that takes an additional option (`--package_json_path`) and sets [`VUE_CLI_CONTEXT`](https://github.com/vuejs/vue-cli/issues/3152#issuecomment-448892609) accordingly without even touching the current working directory.

**Comment by weixiao-huang** [comment] 2020-04-25 06:23
@dubov94  See this: https://github.com/weixiao-huang/bazel-vue-example
If I use `bazel build portal:build`, it will hang

**Comment by dubov94** [comment] 2020-04-25 08:03
@alexeagle Unfortunately `$(@D)` is relative to `execroot/workspace`, and `vue-cli-service build` resolves relative `--dest` based on `package.json` location (which is either `VUE_CLI_CONTEXT` or just `process.cwd()`), so generated files end up in a wrong place.

We could obviously prepend `$(@D)` with enough double dots to get to `execroot/workspace` eventually, but this does not look nice at all and, IMO, requires too much user knowledge about how [output directories](https://docs.bazel.build/versions/master/output_directories.html) work.

**Comment by dubov94** [comment] 2020-04-25 08:26
@weixiao-huang Thank you, I was able to reproduce the problem, and I don't see an immediate solution. For now you can use [vue-cli-launcher](https://npmjs.com/package/vue-cli-launcher) instead of `vue-cli-service`.

@alexeagle Isn't actually `--node_options` supposed to be a part of `tool` somehow?

**Comment by alexeagle** [comment] 2020-04-27 14:50
Yeah messing up the output directory is one of the follow-on path issues from changing the working directory that I mentioned earlier, prevents us from making this chdir trick built-in right now.

`--node_options` shouldn't be part of `tool` if you want to be able to pass different options to different invocations of the tool, right?

@weixiao-huang I don't think your hang is related to the original issue of setting the working directory. Note that if you want to debug by calling the bazel exec command directly, you must also run it in the same working directory (this is why bazel --subcommands prints the command wrapped in a subshell with a `cd`)

Let's keep this issue specifically for the working directory, I think there are other issues about vue (would be great to have an example checked in)

**Comment by dubov94** [comment] 2020-04-27 22:24
I agree that ideally the tool should be target-independent, but in your suggestion aren't we passing `--node_modules=` to `vue-cli-service` rather than Node?

Looks like @weixiao-huang's [bazel-vue-example](https://github.com/weixiao-huang/bazel-vue-example) does not hang if we remove `--node_options=` from `args`.

---

Anyway, even if we manage to find a shortcut for this particular case, it's likely to be quite fragile. Perhaps it shouldn't be handled on `rules_nodejs` level in the first place. We could probably distinguish a class of instruments that expect both inputs and outputs to be located under a single directory containing `package.json`, and implement dedicated tooling for it &mdash; for example, a wrapper creating a temporary directory of the required structure and then copying the results back where they actually are expected.

**Comment by hsyed** [comment] 2020-05-05 09:41
Apologies complete node and JS compilation noob here.Tried the approach above in a few forms, in the form below it hangs:

```py
load("@build_bazel_rules_nodejs//:index.bzl", "npm_package_bin")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

write_file(
    name = "write_chdir_script",
    out = "chdir.js",
    content = ["process.chdir(__dirname)"],
)

npm_package_bin(
    name = "app",
    tool = "@npm//@vue/cli-service/bin:vue-cli-service",
    args = [
        "build",
        "--dest", "$(@D)",
        "--node_options=--require=./$(execpath chdir.js)"
    ],
    data = [
        "@npm//:node_modules",
        "chdir.js"
    ] + glob(["src/**"]),
    output_dir = 1,
    visibility = ["//visibility:private"],
)
```

If I adapt the above to provide the entry point `main.js` file to the vue-cli-service it cannot resolve it. 

I tried to replicate the workaround by executing in the root of our monorepo and get the following: 

```
➜  esqimo-platform git:(sandbox/bazel-js) ✗ ./js/node_modules/.bin/vue-cli-service build js/src/main.js --node_options=--require=js/chdir.js

⠇  Building for production...

 ERROR  Failed to compile with 13 errors                                                                                                                                                                                                                                                                                                                                                                                                                                               10:32:18 AM

Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: cache-loader
You may need to install it.
Failed to resolve loader: css-loader
You may need to install it.
 ERROR  Build failed with errors.
```

**Comment by hsyed** [comment] 2020-05-15 12:37
@alexeagle any thoughts on the best way forward ? 

I think `vue-cli-service` should support a parameter telling it where the project is located. I could open an issue for this ?

**Comment by alexeagle** [comment] 2020-05-21 15:09
Hey, yeah I agree that's a good FR for vue-cli-service, I'd recommend phrasing the issue in terms of "monorepo" rather than mention Bazel since the latter has a narrow audience right now and won't get their attention.

I think for us to dig into the vue-specific parts of this issue, the best way is to add `examples/vue` to this repo so we can have some first-party-maintained bits that we understand and run tests against. Then ppl with vue-specific issues can hand us a repro just in terms of changes to that example which add their use case.

Anyone on the thread have time to contribute that example?

**Comment by dubov94** [comment] 2020-05-21 15:47
I'm pretty sure [vuejs/vue-cli#3150](https://github.com/vuejs/vue-cli/issues/3150) and its references address this, but there hasn't been much activity going on recently.

Do I understand correctly that you are suggesting to add the non-working example to `examples/vue`?

**Comment by Smokrow** [comment] 2020-05-24 10:34
Would the example be a multiproject repo or just for VueJS?

**Comment by alexeagle** [comment] 2020-05-25 16:58
Ideally we add a working VueJS example. There's so much discussion above I'm not sure if there is any working vue setup today?
Even if it's not working, at least we would have a red PR containing a vue app that I can iterate on to fix it.

**Comment by Smokrow** [comment] 2020-05-26 21:13
I am currently setting one up using the vue-cli-service tool. Had a few troubles running the build command though. I will see what I can do. If you want I could just add a standard default Vue application and put some build files in it once I got it working.

**Comment by alexeagle** [comment] 2020-07-05 15:46
#1915 has the vue example.
https://github.com/vuejs/vue-cli/issues/3152 has a possible solution for this that doesn't require chdir.
I'll document/test the chdir userspace workaround as a way to close this issue.

**Closed** 2020-07-05 19:38 UTC
Labels: enhancement, examples, has workaround
