### ISSUE TITLE
See http://tsetse.info/must-type-assert-json-parse link returns a 404

### ISSUE THREAD

**Issue by EliSchleifer** [bazelbuild/rules_nodejs#2404] opened 2021-01-15 20:19 UTC
# 🐞 bug report

### Affected Rule

must-type-assert-json-parse

### Is this a regression?

This rule was added in July..not sure

### Description

Not following this rule results in printing out a link to a page that returns a 404
See http://tsetse.info/must-type-assert-json-parse

## 🔬 Minimal Reproduction

Break rule JSON.parse()

## 🔥 Exception or Error

<pre><code>
error TS21231: [tsetse] type assert `JSON.parse() as SomeExplicitType` for type & optimization safety.
        See http://tsetse.info/must-type-assert-json-parse.

95      let mr: results.MochaResult = JSON.parse(json);
    

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
N/A
  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>
Build label: 4.0.0rc7
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 15 19:18:12 2020 (1608059892)
Build timestamp: 1608059892
Build timestamp as int: 1608059892
  </code>
</pre>

**Rules_nodejs version:**

(Please check that you have matching versions between WORKSPACE file and `@bazel/*` npm packages.)

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by mattem** [comment] 2021-01-18 13:52
Thanks for the report, this is a duplicate of https://github.com/bazelbuild/rules_nodejs/issues/2367 
We can use that issue to track the state of the tsetse docs

**Closed by mattem** 2021-01-18 13:52 UTC

**Comment by EliSchleifer** [comment] 2021-01-18 19:25
Thanks Matt. I think GitHub issues have the worst search. Had attempted to find an existing issue.
