### ISSUE TITLE
Angular 10 followup

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_nodejs#1984] opened 2020-06-30 19:13 UTC
https://github.com/angular/angular/pull/36333
https://github.com/angular/angular/pull/37727

also we should remove our https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular/patches/%40angular%2Bcompiler-cli%2B10.0.0-rc.6.patch and upgrade our example to 10.0.1

**Comment by gregmagolan** [comment] 2020-07-01 00:14
angular/angular#37727 should be unblocked by https://github.com/bazelbuild/rules_nodejs/pull/1987

**Comment by gregmagolan** [comment] 2020-07-15 07:33
Updates:

LinkablePackageInfo update to ng_module landed and released with @angular/bazel 10.1.0-next.0. Updating examples/angular_view_engine.

And https://github.com/angular/angular/pull/37727 update to 2.0.0-rc.2 has one last issue which is the linker bazel-out issue which also causes https://github.com/bazelbuild/rules_nodejs/issues/2035 & https://github.com/bazelbuild/rules_nodejs/issues/2002. Working on the root cause for all three presently.

**Comment by gregmagolan** [comment] 2020-07-17 03:02
angular/angular upgrade all green: https://github.com/angular/angular/pull/37727

**Closed by gregmagolan** 2020-07-17 03:02 UTC
